### ISSUE TITLE
The filter button doesn't work

### ISSUE THREAD

**Issue by oxk4r01** [tintinweb/vscode-inline-bookmarks#26] opened 2020-12-07 11:21 UTC
It doesn't do anything. Bookmarks are permanently shown. No visibility toggle.

**Comment by tintinweb** [comment] 2020-12-09 19:34
Hi @oxk4r01,

which filter functionality are you referring to?

* the "eye" like button in the bookmarks view
* or the `InlineBookmarks: Set View Filter` command?

**Comment by tintinweb** [comment] 2021-01-04 10:45
closing, cannot reproduce.

**Closed as completed by tintinweb** 2021-01-04 10:45 UTC
